create or replace TABLE CUSTOMER_DETAILS (
	CUSTOMER_ID NUMBER(38,0) NOT NULL,
	FIRST_NAME VARCHAR(255),
	LAST_NAME VARCHAR(255),
	EMAIL VARCHAR(255),
	PHONE VARCHAR(20),
	ADDRESS VARCHAR(255),
	primary key (CUSTOMER_ID)
);